############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Solutions"
url = "solution/"
weight = 2

[[main]]
name = "Systems"
url = "system-architecture/"
weight = 3

[[main]]
name = "Products"
url = "product/"
weight = 4

[[main]]
name = "Contact"
url = "contact/"
weight = 5

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Solutions"
url = "solution/"
weight = 2

[[footer]]
name = "Products"
url = "product/"
weight = 3

[[footer]]
name = "Download"
url = "downloads/"
weight = 4

[[footer]]
name = "FAQ"
url = "faq/"
weight = 5

[[footer]]
name = "Contact"
url = "contact/"
weight = 6
