############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
weight = 3
name = "Product"
url = "product/"


[[main]]
weight = 4
name = "Services"
url = "sv/"

[[main]]
weight = 5
name = "Solutions"
url = "solution/"

 
[[main]]
name = "Contact"
url = "contact/"
weight = 6


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Product"
url = "product/"
weight = 3

[[footer]]
name = "Solution"
url = "solution/"
weight = 4

[[footer]]
name = "FAQ"
url = "faq/"
weight = 5

[[footer]]
name = "Contact"
url = "contact/"
weight = 6